# Generated by Django 5.0.2 on 2024-08-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.CharField(max_length=900)),
                ('quote_author', models.CharField(max_length=50)),
                ('quote_year', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('quote_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quotes.quotecategory')),
            ],
        ),
    ]
