# Generated by Django 5.0.2 on 2024-08-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote_category',
            new_name='category',
        ),
    ]
