# Generated by Django 5.0.2 on 2024-08-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_quote_category_quote_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='quotes.quotecategory'),
        ),
    ]
